services:
  eurostar-sleeper-api:
    image: eurostar-sleeper-api
    build: .
    container_name: eurostar-sleeper-api
    restart: unless-stopped
    volumes:
      - .:/app
    environment:
      - PORT=8080
      - HOST=0.0.0.0
      - TZ=Europe/Paris
    networks:
      - spotted-network

networks:
  spotted-network:
    external: true